"""empty message

Revision ID: 1d4db4bf3afe
Revises: 7d67f8986de2
Create Date: 2019-04-01 13:49:22.167000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4db4bf3afe'
down_revision = '7d67f8986de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_name', sa.String(length=32), nullable=True),
    sa.Column('version_information', sa.String(length=32), nullable=True),
    sa.Column('logo', sa.String(length=128), nullable=True),
    sa.Column('copyright', sa.String(length=32), nullable=True),
    sa.Column('user_authentication_mode', sa.String(length=16), nullable=True),
    sa.Column('debug', sa.Boolean(), nullable=True),
    sa.Column('store_log', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('copyright'),
    sa.UniqueConstraint('platform_name'),
    sa.UniqueConstraint('version_information')
    )
    op.drop_table('systemconfiguration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systemconfiguration',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('platform_name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('version_information', sa.VARCHAR(length=32), nullable=True),
    sa.Column('logo', sa.VARCHAR(length=128), nullable=True),
    sa.Column('copyright', sa.VARCHAR(length=32), nullable=True),
    sa.Column('user_authentication_mode', sa.VARCHAR(length=16), nullable=True),
    sa.Column('DEBUG', sa.BOOLEAN(), nullable=True),
    sa.Column('STORE_LOG', sa.VARCHAR(length=100), nullable=True),
    sa.CheckConstraint(u'"DEBUG" IN (0, 1)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('copyright'),
    sa.UniqueConstraint('platform_name'),
    sa.UniqueConstraint('version_information')
    )
    op.drop_table('system_config')
    # ### end Alembic commands ###
