"""empty message

Revision ID: 212689126271
Revises: 74726618b373
Create Date: 2019-04-15 18:07:12.263000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212689126271'
down_revision = '74726618b373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vcenter_tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('dc_host_folder_mor_name', sa.String(length=255), nullable=True),
    sa.Column('dc_mor_name', sa.String(length=255), nullable=True),
    sa.Column('dc_oc_name', sa.String(length=255), nullable=True),
    sa.Column('dc_vm_folder_mor_name', sa.String(length=255), nullable=True),
    sa.Column('mor_name', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cluster_mor_name', sa.String(length=255), nullable=True),
    sa.Column('cluster_oc_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'cloud_platform', ['platform_name'])
    op.drop_index('cloud_platform_type_name_uindex', table_name='cloud_platform_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('cloud_platform_type_name_uindex', 'cloud_platform_type', ['name'], unique=1)
    op.drop_constraint(None, 'cloud_platform', type_='unique')
    op.drop_table('vcenter_tree')
    # ### end Alembic commands ###
