"""empty message

Revision ID: 7d67f8986de2
Revises: a4cd21ed95dd
Create Date: 2019-03-29 19:18:05.543000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d67f8986de2'
down_revision = 'a4cd21ed95dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ico', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('identifier', sa.String(length=20), nullable=True),
    sa.Column('id_hide', sa.Boolean(), nullable=True),
    sa.Column('is_hide_children', sa.Boolean(), nullable=True),
    sa.Column('important', sa.String(length=20), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    # ### end Alembic commands ###
