"""empty message

Revision ID: 9bce5d63c1ae
Revises: 7f09533b1f74
Create Date: 2019-03-29 09:53:38.391000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bce5d63c1ae'
down_revision = '7f09533b1f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('remarks', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'remarks')
    # ### end Alembic commands ###
