"""empty message

Revision ID: f0cd09d7fc57
Revises: 91e80a6054e4
Create Date: 2019-04-17 15:31:51.715000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0cd09d7fc57'
down_revision = '91e80a6054e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vcenter_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('vm_name', sa.String(length=255), nullable=False),
    sa.Column('vm_mor_name', sa.String(length=255), nullable=False),
    sa.Column('template', sa.Boolean(), nullable=False),
    sa.Column('vm_path_name', sa.String(length=255), nullable=False),
    sa.Column('memory', sa.String(length=40), nullable=False),
    sa.Column('cpu', sa.String(length=40), nullable=False),
    sa.Column('num_ethernet_cards', sa.Integer(), nullable=False),
    sa.Column('num_virtual_disks', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('instance_uuid', sa.String(length=40), nullable=False),
    sa.Column('guest_id', sa.String(length=255), nullable=False),
    sa.Column('guest_full_name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=40), nullable=False),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vcenter_instance')
    # ### end Alembic commands ###
